name: DevHub
description: "DevHub Flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  dio: ^5.8.0+1
  http: ^1.2.0
  shared_preferences: ^2.2.2
  openid_client: ^0.4.7
  url_launcher: ^6.3.0
  app_links: ^6.3.0
  crypto: ^3.0.3
  intl: ^0.19.0
  uuid: ^4.4.0
  flutter_chat_bubble: ^2.0.2
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.0
  jwt_decode: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true
  # optionally, as transparency is not allowed on app store
  # remove_alpha_ios: true